//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Transport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_reservation { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idTrajet { get; set; }
    
        public virtual client client { get; set; }
        public virtual trajet trajet { get; set; }
    }
}
