//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Transport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class societe
    {
        public int id { get; set; }
        public string nom { get; set; }
        public Nullable<int> tele { get; set; }
        public string adresse { get; set; }
        public string login_societe { get; set; }
        public string mdp_societe { get; set; }
    }
}
