//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Transport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class societe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public societe()
        {
            this.trajets = new HashSet<trajet>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public Nullable<int> tele { get; set; }
        public string adresse { get; set; }
        public string login { get; set; }
        public string mdp { get; set; }
        public Nullable<int> idCar { get; set; }
    
        public virtual car car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trajet> trajets { get; set; }
    }
}
