//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Transport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trajet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trajet()
        {
            this.reservations = new HashSet<reservation>();
        }
    
        public int id { get; set; }
        public string Ville_depart { get; set; }
        public string Ville_arrive { get; set; }
        public Nullable<System.DateTime> Date_depart { get; set; }
        public Nullable<int> Nbr_heure { get; set; }
        public Nullable<int> idCar { get; set; }
        public Nullable<int> idSociete { get; set; }
        public Nullable<int> idVille { get; set; }
    
        public virtual car car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
        public virtual societe societe { get; set; }
        public virtual ville ville { get; set; }
    }
}
